module.exports  = [
  {
    type: "adv",
    ID: "A99",
    name: "Adam",
    surname: "Man",
    password: "me",
  },
  {
    type: "adv",
    ID: "A001",
    name: "Lisa",
    surname: "Man",
    password: "me",
  },
  {
    type: "adv",
    ID: "A002",
    name: "Somporn",
    surname: "Youngjean",
    password: "pornporn",
  },
  {
    type: "adv",
    ID: "A003",
    name: "Loura",
    surname: "Louren",
    password: "1234loura",
  },
  {
    type: "adv",
    ID: "A004",
    name: "Sompomg",
    surname: "Looksomchai",
    password: "OyeOyeOOye",
  },
  {
    type: "adv",
    ID: "A005",
    name: "koi",
    surname: "The",
    password: "chakaimook",
  },
  {
    type: "std",
    ID: "600510569",
    name: "Meehoi",
    surname: "Eiei",
    advID: "A99",
    password: "4568",
  },
  {
    type: "std",
    ID: "600510566",
    name: "Patteera",
    surname: "thisri",
    advID: "A99",
    password: "ice1010",
  },
  {
    type: "std",
    ID: "600510573",
    name: "Rawiprair",
    surname: "Manowarawut",
    advID: "A001",
    password: "prairranny",
  },
  {
    type: "std",
    ID: "610510569",
    name: "Kooning",
    surname: "Inking",
    advID: "A003",
    password: "nonginkdekPice",
  },
  {
    type: "std",
    ID: "610510577",
    name: "Dora",
    surname: "Swiper",
    advID: "A004",
    password: "inforest",
  },
  {
    type: "std",
    ID: "600510112",
    name: "Jumaporn",
    surname: "Le",
    advID: "A005",
    password: "slim",
  },
  {
    type: "std",
    ID: "600510590",
    name: "Poo",
    surname: "Abdul",
    advID: "A99",
    password: "porIO",
  },
  {
    type: "std",
    ID: "600510010",
    name: "Ora",
    surname: "Abdul",
    advID: "A99",
    password: "look09",
  },
  {
    type: "std",
    ID: "600510511",
    name: "Teepee",
    surname: "Rasa",
    advID: "A001",
    password: "lookerIO",
  },
  {
    type: "std",
    ID: "600510593",
    name: "Jarernpong",
    surname: "Pan",
    advID: "A003",
    password: "pongjarern",
  },
  {
    type: "std",
    ID: "600510558",
    name: "Pongpan",
    surname: "Ngampong",
    advID: "A004",
    password: "ngamngon",
  },
  {
    type: "std",
    ID: "600510589",
    name: "Hwernhwer",
    surname: "Manoo",
    advID: "A005",
    password: "hwernhwern",
  },
  {
    type: "std",
    ID: "600510676",
    name: "Boonchu",
    surname: "Boriboon",
    advID: "A003",
    password: "saraau",
  },
]
